-- Lv2 

-- MySQL
SELECT *
FROM FOOD_PRODUCT 
ORDER BY PRICE DESC
LIMIT 1;

SELECT * 
FROM FOOD_PRODUCT 
WHERE PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT);


-- Oracle
SELECT *
FROM FOOD_PRODUCT 
ORDER BY PRICE DESC
FETCH FIRST 1 ROWS ONLY;

SELECT * 
FROM FOOD_PRODUCT 
WHERE PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT);