-- MYSQL
SELECT UG.USER_ID, UG.NICKNAME, SUM(UB.PRICE) AS TOTAL_SALES
FROM
    USED_GOODS_BOARD UB INNER JOIN USED_GOODS_USER UG
        ON UB.WRITER_ID = UG.USER_ID
WHERE
    STATUS = "DONE"
GROUP BY
    UB.WRITER_ID
HAVING 
    TOTAL_SALES >= 700000
ORDER BY
    TOTAL_SALES ASC;